import type { IncomingMessage, ServerResponse } from "node:http";

export default function handler(_req: IncomingMessage, res: ServerResponse) {
  res.statusCode = 200;
  res.setHeader("content-type", "text/html; charset=utf-8");
  res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>OrbitFS Products</title><style>
body{margin:0;background:#08090d;color:#eef0f5;font:14px system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:28px}h1{margin:0 0 6px}.sub{color:#8f95a3}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px;margin-top:22px}.card{background:#11131a;border:1px solid #252936;border-radius:14px;padding:18px}.row{display:flex;gap:10px;align-items:center;justify-content:space-between}.pill{padding:4px 8px;border-radius:999px;background:#1d3327;color:#8ee0ad}.muted{color:#8f95a3}button{background:#e9edf5;color:#101218;border:0;border-radius:9px;padding:9px 12px;font-weight:700;cursor:pointer}button.secondary{background:#242936;color:#eef0f5}.toolbar{display:flex;gap:10px;margin-top:18px;flex-wrap:wrap}.editor{position:fixed;inset:0;background:#08090dcc;display:none;align-items:center;justify-content:center;padding:18px}.panel{width:min(720px,100%);max-height:90vh;overflow:auto;background:#11131a;border:1px solid #303442;border-radius:16px;padding:20px}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form label{display:grid;gap:5px}.wide{grid-column:1/-1}input,textarea,select{background:#0b0d12;color:#eef0f5;border:1px solid #303442;border-radius:8px;padding:10px}textarea{min-height:80px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}@media(max-width:650px){.form{grid-template-columns:1fr}}
</style></head><body><main><div class="row"><div><h1>Product Catalogue</h1><div class="sub">Fully configurable licence products and entitlement defaults.</div></div><button onclick="openEditor()">+ New Product</button></div><div id="status" class="sub" style="margin-top:18px">Loading…</div><div id="grid" class="grid"></div></main><div id="editor" class="editor"><div class="panel"><div class="row"><h2 id="title">New Product</h2><button class="secondary" onclick="closeEditor()">Close</button></div><div class="form"><label>Code<input id="code"></label><label>Name<input id="name"></label><label>Slug<input id="slug"></label><label>Type<select id="productType"><option>component</option><option>addon</option><option>bundle</option><option>service</option></select></label><label>Component Key<input id="componentKey" placeholder="orbitfs_base"></label><label>Runtime<select id="runtime"><option>panel</option><option>engine</option><option>external</option></select></label><label>Price<input id="price" type="number" step="0.01"></label><label>Currency<input id="currency" value="AUD"></label><label>Billing<select id="billing"><option>one_time</option><option>monthly</option><option>yearly</option></select></label><label>Max Installations<input id="maxInstallations" type="number" min="1" value="1"></label><label>Release Channel<select id="channel"><option>stable</option><option>beta</option><option>nightly</option></select></label><label>Duration Days<input id="duration" type="number"></label><label class="wide">Short Description<input id="short"></label><label class="wide">Description<textarea id="description"></textarea></label><label class="wide">Features JSON<textarea id="features">[]</textarea></label><label class="wide">Entitlement Defaults JSON<textarea id="entitlements">{}</textarea></label><label class="wide">Metadata JSON<textarea id="metadata">{}</textarea></label><label><input id="active" type="checkbox" checked> Active</label><label><input id="purchasable" type="checkbox" checked> Purchasable</label><label><input id="public" type="checkbox" checked> Public</label><label><input id="requiresEngine" type="checkbox"> Requires Engine</label><label><input id="requiresBase" type="checkbox" checked> Requires Base</label></div><div class="actions"><button class="secondary" onclick="closeEditor()">Cancel</button><button onclick="save()">Save Product</button></div></div></div><script>
let products=[],editing=null;const token=()=>sessionStorage.getItem('orbitfs_admin_access_token')||'';const $=id=>document.getElementById(id);const api=(url,opt={})=>fetch(url,{...opt,headers:{'content-type':'application/json',authorization:'Bearer '+token(),...(opt.headers||{})}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d});
async function load(){try{const d=await api('/api/products?admin=1');products=d.products||[];$('status').textContent=products.length+' products';$('grid').innerHTML=products.map(p=>'<div class="card"><div class="row"><b>'+esc(p.name)+'</b><span class="pill">'+(p.active?'Active':'Inactive')+'</span></div><p class="muted">'+esc(p.code)+' · '+esc(p.runtime)+' · '+esc(p.releaseChannel)+'</p><p>'+esc(p.description||'No description')+'</p><div class="row"><span>'+esc(p.priceCurrency)+' '+Number(p.priceAmount||0).toFixed(2)+'</span><button class="secondary" onclick="edit('+JSON.stringify(p.id)+')">Edit</button></div></div>').join('')}catch(e){$('status').textContent=e.message}}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openEditor(p={}){editing=p.id||null;$('title').textContent=editing?'Edit Product':'New Product';for(const [id,key] of [['code','code'],['name','name'],['slug','slug'],['componentKey','componentKey'],['price','priceAmount'],['currency','priceCurrency'],['maxInstallations','maxInstallations'],['duration','durationDays'],['short','shortDescription'],['description','description']])$(id).value=p[key]??'';$('productType').value=p.productType||'component';$('runtime').value=p.runtime||'engine';$('billing').value=p.billingInterval||'one_time';$('channel').value=p.releaseChannel||'stable';$('features').value=JSON.stringify(p.features||[],null,2);$('entitlements').value=JSON.stringify(p.entitlementDefaults||{},null,2);$('metadata').value=JSON.stringify(p.metadata||{},null,2);for(const [id,key,def] of [['active','active',true],['purchasable','purchasable',true],['public','public',true],['requiresEngine','requiresEngine',false],['requiresBase','requiresBase',true]])$(id).checked=p[key]??def;$('editor').style.display='flex'}
function edit(id){openEditor(products.find(p=>p.id===id)||{})}function closeEditor(){$('editor').style.display='none'}
async function save(){try{const json=id=>{try{return JSON.parse($(id).value||'{}')}catch{throw Error(id+' contains invalid JSON')}};const p={code:$('code').value,name:$('name').value,slug:$('slug').value,productType:$('productType').value,componentKey:$('componentKey').value||null,runtime:$('runtime').value,priceAmount:Number($('price').value||0),priceCurrency:$('currency').value,billingInterval:$('billing').value,maxInstallations:Number($('maxInstallations').value||1),durationDays:$('duration').value?Number($('duration').value):null,releaseChannel:$('channel').value,shortDescription:$('short').value,description:$('description').value,features:json('features'),entitlementDefaults:json('entitlements'),metadata:json('metadata'),active:$('active').checked,purchasable:$('purchasable').checked,public:$('public').checked,requiresEngine:$('requiresEngine').checked,requiresBase:$('requiresBase').checked};await api(editing?'/api/products?id='+encodeURIComponent(editing):'/api/products',{method:editing?'PATCH':'POST',body:JSON.stringify(p)});closeEditor();load()}catch(e){alert(e.message)}}load();
</script></body></html>`);
}
