import { readFileSync } from "node:fs";
import type { IncomingMessage, ServerResponse } from "node:http";

/** Canonical /admin entry. The complete admin UI lives in web/admin.html. */
export default function admin(_req: IncomingMessage, res: ServerResponse) {
  try {
    let html = readFileSync(new URL("../web/admin.html", import.meta.url), "utf8");
    html = html.replaceAll("/api/v1", "/api/license/v1");
    html = html.replace("</body>", `<script>
window.setApiBases=function(){const base=location.origin+'/api';const a=document.getElementById("apiBase");if(a)a.value=base;const v=document.getElementById("apiVersionedBase");if(v)v.value=base+'/license/v1';const h=document.getElementById("authorityHost");if(h)h.textContent=location.host;};
window.renderReleaseSources=function(){if(document.getElementById("baseSource"))document.getElementById("baseSource").innerHTML='<b>Base deployment source</b><span>lucaskerim123/V1-vercel-base / base-release · latest commit loaded from License Master</span>';if(document.getElementById("updateSource"))document.getElementById("updateSource").innerHTML='<b>Update release source</b><span>lucaskerim123/V1-vercel-engine / release-updates · latest commit loaded from License Master</span>';};
window.sourceBranch=function(mode){return mode==='base'?'base-release':'release-updates'};
window.loadReleaseSources=async function(){try{const get=async kind=>{const r=await fetch('/api/admin-extended?action=releaseSource&kind='+encodeURIComponent(kind),{headers:{authorization:'Bearer '+token,'x-release-kind':kind}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Unable to read release source');return d.source||{};};releaseSources.base=await get('base');releaseSources.update=await get('update');renderReleaseSources();if(document.getElementById("baseSource"))document.getElementById("baseSource").innerHTML='<b>Base deployment source</b><span>'+esc(releaseSources.base.repo||'lucaskerim123/V1-vercel-base')+' / '+esc(releaseSources.base.branch||'base-release')+' · '+esc(releaseSources.base.shortSha||'—')+' · '+esc(releaseSources.base.message||'No commits')+'</span>';if(document.getElementById("updateSource"))document.getElementById("updateSource").innerHTML='<b>Update release source</b><span>'+esc(releaseSources.update.repo||'lucaskerim123/V1-vercel-engine')+' / '+esc(releaseSources.update.branch||'release-updates')+' · '+esc(releaseSources.update.shortSha||'—')+' · '+esc(releaseSources.update.message||'No commits')+'</span>';}catch(e){['baseSource','updateSource'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML='<b>Release source unavailable</b><span>'+esc(e.message||e)+'</span>'})}};
function lmMountManagers(){try{const settings=document.getElementById('api-settings');if(settings&&!document.getElementById('lmSettingsActions')){const card=settings.querySelector('.card');if(card){const box=document.createElement('div');box.id='lmSettingsActions';box.className='card';box.style.marginTop='12px';box.innerHTML='<div class="head"><div><h2>License Master Authority Configuration</h2><p class="sub">Canonical settings used by the V2 licensing API and signed entitlements.</p></div><button class="btn primary" type="button" onclick="lmSaveSettings()">Save settings</button></div><div class="grid cols3"><div class="field"><label>API state</label><select id="lmEnabled"><option value="true">Online</option><option value="false">Disabled</option></select></div><div class="field"><label>Mode</label><select id="lmMode"><option value="online">Online</option><option value="offline">Offline grace</option><option value="maintenance">Maintenance</option></select></div><div class="field"><label>Allow offline grace</label><select id="lmOfflineGrace"><option value="true">Yes</option><option value="false">No</option></select></div><div class="field"><label>Issuer</label><input id="lmIssuer"></div><div class="field"><label>Audience</label><input id="lmAudience"></div><div class="field"><label>Entitlement TTL (seconds)</label><input id="lmTtl" type="number"></div><div class="field"><label>Grace period (seconds)</label><input id="lmGrace" type="number"></div><div class="field"><label>API base</label><input id="lmApiBase" readonly></div><div class="field"><label>API version</label><input value="v1" readonly></div></div><p id="lmSettingsStatus" class="small"></p>';settings.appendChild(box);}}lmRefreshSettings()}catch(e){console.error(e)}}
window.lmRefreshSettings=async function(){try{const r=await fetch('/api/admin/license-master/settings',{headers:{authorization:'Bearer '+token}});const x=await r.json();if(!r.ok)throw Error(x.error||'Unable to load License Master settings');const s=x.settings||{};const q=id=>document.getElementById(id);if(q('lmIssuer'))q('lmIssuer').value=s.issuer||'orbitfs-license-master';if(q('lmAudience'))q('lmAudience').value=s.audience||'orbitfs-runtime';if(q('lmTtl'))q('lmTtl').value=s.entitlement_ttl_seconds||10800;if(q('lmGrace'))q('lmGrace').value=s.grace_seconds??604800;if(q('lmEnabled'))q('lmEnabled').value=s.enabled===false?'false':'true';if(q('lmMode'))q('lmMode').value=s.api_mode||'online';if(q('lmOfflineGrace'))q('lmOfflineGrace').value=s.allow_offline_grace===false?'false':'true';if(q('lmApiBase'))q('lmApiBase').value=location.origin+'/api/license/v1';if(q('lmSettingsStatus'))q('lmSettingsStatus').textContent='Connected to canonical License Master API · revision '+String(s.revision||'—');}catch(e){const s=document.getElementById('lmSettingsStatus');if(s)s.textContent=e.message}};
window.lmSaveSettings=async function(){try{const q=id=>document.getElementById(id);const body={enabled:q('lmEnabled').value==='true',api_mode:q('lmMode').value,allow_offline_grace:q('lmOfflineGrace').value==='true',issuer:q('lmIssuer').value.trim(),audience:q('lmAudience').value.trim(),entitlement_ttl_seconds:Number(q('lmTtl').value),grace_seconds:Number(q('lmGrace').value)};const r=await fetch('/api/admin/license-master/settings',{method:'PATCH',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Unable to save License Master settings');toast('License Master API settings saved',false);await lmRefreshSettings()}catch(e){toast(e.message,true)}};
setApiBases();setTimeout(()=>{window.loadReleaseSources();lmMountManagers()},0);
</script></body>`);
    res.statusCode=200;
    res.setHeader("content-type", "text/html; charset=utf-8");
    res.setHeader("cache-control", "no-store, max-age=0");
    res.end(html);
  } catch(error) {
    console.error("Failed to load License Master admin UI",error);
    res.statusCode=500;
    res.setHeader("content-type", "application/json; charset=utf-8");
    res.end(JSON.stringify({error:"Admin UI unavailable"}));
  }
}
