import { Pool } from "pg";
import type { IncomingMessage, ServerResponse } from "node:http";

const DATABASE_URL=String(process.env.DATABASE_URL||"").replace(/[?&]sslmode=[^&]+/i,"");
const db=DATABASE_URL?new Pool({connectionString:DATABASE_URL,max:3,ssl:{rejectUnauthorized:false}}):null;
const MASTER=process.env.MASTER_API_TOKEN||"";
const BILLING=process.env.BILLING_API_TOKEN||"";
const STORE_URL=(process.env.BILLING_STORE_API_URL||"").replace(/\/$/,"");
const STORE_TOKEN=process.env.BILLING_STORE_API_TOKEN||"";
const STORE_PATH=process.env.BILLING_STORE_RELEASE_DRAFT_PATH||"/api/internal/master/release-drafts";
const SUPABASE_URL=(process.env.SUPABASE_URL||"").replace(/\/$/,"");
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||"";

type Role="master"|"billing";
type Row=Record<string,any>;
const json=(res:ServerResponse,status:number,value:unknown)=>{res.statusCode=status;res.setHeader("content-type","application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.end(JSON.stringify(value));};
const bearer=(req:IncomingMessage)=>String(req.headers.authorization||"").replace(/^Bearer\s+/i,"").trim();
const role=(req:IncomingMessage):Role|null=>{const t=bearer(req);if(MASTER&&t===MASTER)return"master";if(BILLING&&t===BILLING)return"billing";return null;};
const query=async<T extends Row=Row>(sql:string,args:unknown[]=[])=>{if(!db)throw Error("Database is not configured");return db.query<T>(sql,args);};
const audit=async(id:string,action:string,actor:string,detail:Row={})=>query("insert into audit_log(id,entity_type,entity_id,action,actor_ref,detail) values(gen_random_uuid(),'release',$1,$2,$3,$4)",[id,action,actor,detail]);
const semver=/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;
const parsed=(v:string)=>{const m=semver.exec(v.trim());if(!m)return null;return{major:+m[1],minor:+m[2],patch:+m[3],pre:m[4]?m[4].split("."):[]};};
const cmp=(a:string,b:string)=>{const x=parsed(a),y=parsed(b);if(!x||!y)return null;for(const k of ["major","minor","patch"] as const)if(x[k]!==y[k])return x[k]>y[k]?1:-1;if(!x.pre.length&&!y.pre.length)return 0;if(!x.pre.length)return 1;if(!y.pre.length)return-1;for(let i=0;i<Math.max(x.pre.length,y.pre.length);i++){if(i>=x.pre.length)return-1;if(i>=y.pre.length)return 1;const A=x.pre[i],B=y.pre[i];if(A===B)continue;const an=/^\d+$/.test(A),bn=/^\d+$/.test(B);if(an&&bn)return+A>+B?1:-1;if(an)return-1;if(bn)return 1;return A>B?1:-1;}return 0;};
const storeShape=(r:Row,d?:Row)=>({id:r.id,component:r.component,version:r.version,channel:r.channel,status:r.status,title:r.title,description:r.description,changelog:r.changelog,customerNotes:r.customer_notes,severity:r.severity,required:r.required,rollout:r.rollout,minimumVersion:r.minimum_version,rollbackVersion:r.rollback_version,schemaVersion:r.schema_version,minimumSchemaVersion:r.minimum_schema_version,updateStrategy:r.update_strategy,components:r.components,manifest:r.manifest,compatibility:r.compatibility,sourceCommit:r.source_commit,artifact:{path:r.artifact_path,sha256:r.artifact_sha256,size:r.artifact_size,contentType:r.artifact_content_type,downloadEndpoint:`/api/release-handoff?action=artifact-url&id=${encodeURIComponent(r.id)}`},finalizedAt:r.finalized_at,automationSource:r.automation_source,delivery:d||null});
const sendStore=async(r:Row)=>{const d=(await query("insert into release_store_deliveries(release_id,status,attempts) values($1,'pending',0) on conflict(release_id) do update set status='pending',updated_at=now() returning *",[r.id])).rows[0] as Row;if(!STORE_URL||!STORE_TOKEN)return{delivery:d,sent:false,reason:"Billing Store integration is not configured"};try{const resp=await fetch(`${STORE_URL}${STORE_PATH}`,{method:"POST",headers:{authorization:`Bearer ${STORE_TOKEN}`,"content-type":"application/json","x-orbitfs-master-event":"release.draft.ready"},body:JSON.stringify({event:"release.draft.ready",schemaVersion:1,source:"orbitfs-license-master-v2",release:storeShape(r)})});const data=await resp.json().catch(()=>({}));if(!resp.ok)throw Error(`Billing Store returned HTTP ${resp.status}`);const updated=(await query("update release_store_deliveries set status='sent',attempts=attempts+1,response=$1,last_error=null,delivered_at=now(),updated_at=now() where release_id=$2 returning *",[data,r.id])).rows[0];await audit(r.id,"store_handoff_sent","master",{response:data});return{delivery:updated,sent:true,response:data};}catch(e){const message=e instanceof Error?e.message:String(e);const updated=(await query("update release_store_deliveries set status='failed',attempts=attempts+1,last_error=$1,updated_at=now() where release_id=$2 returning *",[message,r.id])).rows[0];await audit(r.id,"store_handoff_failed","master",{error:message});return{delivery:updated,sent:false,error:message};}};
const signedUrl=async(path:string)=>{if(!SUPABASE_URL||!SUPABASE_KEY)throw Error("Supabase storage is not configured");const r=await fetch(`${SUPABASE_URL}/storage/v1/object/sign/orbitfs-license-master-releases/${path}`,{method:"POST",headers:{authorization:`Bearer ${SUPABASE_KEY}`,apikey:SUPABASE_KEY,"content-type":"application/json"},body:JSON.stringify({expiresIn:600})});if(!r.ok)throw Error("Release download URL creation failed");const d=await r.json() as Row;const u=String(d.signedURL||d.signedUrl||d.signed_url||"");if(!u)throw Error("Release download URL was not returned");return u.startsWith("http")?u:`${SUPABASE_URL}/storage/v1${u}`;};
export default async function handler(req:IncomingMessage,res:ServerResponse){try{const r=role(req);if(!r)return json(res,401,{error:"Unauthorized"});if(!db)return json(res,503,{error:"Database is not configured"});const u=new URL(req.url||"/","http://localhost");const action=u.searchParams.get("action")||"drafts";const id=u.searchParams.get("id")||"";
if(req.method==="GET"&&action==="drafts"){const rows=(await query("select r.*,d.status as delivery_status,d.attempts as delivery_attempts,d.last_error as delivery_error,d.delivered_at,d.acknowledged_at from releases r left join release_store_deliveries d on d.release_id=r.id where r.status='ready_for_store' order by r.finalized_at asc limit 200")).rows;return json(res,200,{releases:rows.map((x:any)=>({...storeShape(x),deliveryStatus:x.delivery_status||"pending",deliveryAttempts:x.delivery_attempts||0,deliveryError:x.delivery_error||null,deliveredAt:x.delivered_at||null,acknowledgedAt:x.acknowledged_at||null}))});}
if(req.method==="GET"&&action==="artifact-url"){const row=(await query("select id,artifact_path,artifact_sha256,artifact_size from releases where id=$1",[id])).rows[0] as Row|undefined;if(!row)return json(res,404,{error:"Release not found"});if(!row.artifact_path)return json(res,409,{error:"Release artifact is missing"});return json(res,200,{releaseId:id,sha256:row.artifact_sha256,size:row.artifact_size,downloadUrl:await signedUrl(row.artifact_path),expiresIn:600});}
if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});
if(action==="finalize"||action==="auto-finalize"){if(r!=="master")return json(res,403,{error:"Only License Master can finalize releases"});const row=(await query("select * from releases where id=$1",[id])).rows[0] as Row|undefined;if(!row)return json(res,404,{error:"Release not found"});if(row.status!=="validated")return json(res,409,{error:`Release must be validated before Store handoff (current status: ${row.status})`});if(!parsed(String(row.version||"")))return json(res,422,{error:"Release version must be a valid semantic version"});if(action==="auto-finalize"){const s=(await query("select release_automation_enabled,auto_finalize_base,auto_finalize_updates from master_license_settings where id='primary'")).rows[0] as Row||{};const enabled=String(row.channel)==="base"?s.auto_finalize_base===true:s.auto_finalize_updates===true;if(s.release_automation_enabled!==true||!enabled)return json(res,409,{error:"Automatic release finalization is disabled"});}const previous=(await query("select version from releases where component=$1 and channel=$2 and status in ('validated','ready_for_store','published') and id<>$3 order by published_at desc nulls last,updated_at desc limit 1",[row.component,row.channel,id])).rows[0] as Row|undefined;if(previous?.version&&cmp(String(row.version),String(previous.version))<=0)return json(res,422,{error:"Release version is not greater than the previous release",previousVersion:previous.version,currentVersion:row.version});const finalized=(await query("update releases set status='ready_for_store',customer_visible=false,finalized_at=now(),finalized_by=$1,automation_source=$2,updated_at=now() where id=$3 returning *",[r,action==="auto-finalize"?"automation":"manual",id])).rows[0] as Row;await audit(id,"finalized_for_store",r,{automatic:action==="auto-finalize"});return json(res,200,{release:finalized,...await sendStore(finalized)});}
if(action==="publish"){if(r!=="billing")return json(res,403,{error:"Only the V2 Billing Store can publish a customer-visible release"});const row=(await query("select * from releases where id=$1",[id])).rows[0] as Row|undefined;if(!row)return json(res,404,{error:"Release not found"});if(row.status!=="ready_for_store")return json(res,409,{error:"Release must be ready_for_store before Billing Store publication",status:row.status});const published=(await query("update releases set status='published',customer_visible=true,published_at=now(),published_by='billing',updated_at=now() where id=$1 returning *",[id])).rows[0];await query("update release_store_deliveries set status='acknowledged',acknowledged_at=now(),updated_at=now() where release_id=$1",[id]);await audit(id,"published","billing",{});return json(res,200,{release:published});}
if(action==="retry"){if(r!=="master")return json(res,403,{error:"Only License Master can retry Store handoff"});const row=(await query("select * from releases where id=$1 and status='ready_for_store'",[id])).rows[0] as Row|undefined;if(!row)return json(res,404,{error:"Ready release not found"});return json(res,200,{release:row,...await sendStore(row)});}
return json(res,400,{error:"Unknown release handoff action"});
}catch(e){return json(res,500,{error:e instanceof Error?e.message:String(e)})}}
