import { Pool } from "pg";
import type { IncomingMessage, ServerResponse } from "node:http";

const dbUrl=String(process.env.DATABASE_URL||"").replace(/[?&]sslmode=[^&]+/i,"");
const db=dbUrl?new Pool({connectionString:dbUrl,max:3,ssl:{rejectUnauthorized:false}}):null;
const MASTER=process.env.MASTER_API_TOKEN||"", BILLING=process.env.BILLING_API_TOKEN||"", DEPLOYER=process.env.DEPLOYER_API_TOKEN||"";
const GITHUB_TOKEN=process.env.GITHUB_TOKEN||process.env.GH_TOKEN||"";
const RELEASE_BASE_REPOSITORY="lucaskerim123/V1-vercel-base";
const RELEASE_BASE_BRANCH="base-release";
const RELEASE_UPDATE_REPOSITORY="lucaskerim123/V1-vercel-engine";
const RELEASE_UPDATE_BRANCH="release-updates";
const json=(res:ServerResponse,status:number,value:unknown)=>{res.statusCode=status;res.setHeader("content-type","application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.end(JSON.stringify(value));};
const bearer=(req:IncomingMessage)=>String(req.headers.authorization||"").replace(/^Bearer\s+/i,"").trim();
const role=(req:IncomingMessage)=>{const t=bearer(req);if(t&&t===MASTER)return "master";if(t&&t===BILLING)return "billing";if(t&&t===DEPLOYER)return "deployer";return null};
const body=(req:IncomingMessage):Promise<unknown>=>new Promise<unknown>((resolve,reject)=>{const c:Buffer[]=[];req.on("data",x=>c.push(Buffer.from(x)));req.on("end",()=>{try{resolve(c.length?JSON.parse(Buffer.concat(c).toString("utf8")):{});}catch{reject(new Error("Request body must be valid JSON"));}});req.on("error",reject);});
async function source(repo:string,branch:string){if(!GITHUB_TOKEN)throw new Error("GITHUB_TOKEN is not configured");const r=await fetch(`https://api.github.com/repos/${repo}/commits?sha=${encodeURIComponent(branch)}&per_page=1`,{headers:{accept:"application/vnd.github+json",authorization:`Bearer ${GITHUB_TOKEN}`,"x-github-api-version":"2022-11-28","user-agent":"OrbitFS-License-Master-V2"}});const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(String(d?.message||"GitHub source lookup failed"));const c=Array.isArray(d)?d[0]:null;if(!c?.sha)throw new Error(`No commits found for ${repo} / ${branch}`);return {repo,branch,sha:String(c.sha),shortSha:String(c.sha).slice(0,12),message:String(c.commit?.message||"").split("\n")[0],date:c.commit?.author?.date||c.commit?.committer?.date||null,url:c.html_url||`https://github.com/${repo}/commit/${c.sha}`};}
export default async function releaseCapture(req:IncomingMessage,res:ServerResponse){try{const r=role(req);if(!r||!( ["master","billing"].includes(r)))return json(res,401,{error:"Unauthorized"});if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});if(!db)return json(res,503,{error:"Database is not configured"});const input=await body(req) as Record<string,unknown>;const kind=String(input.kind||"update").toLowerCase()==="base"?"base":"update";const component=kind==="base"?"orbitfs_base":"orbitfs_mcp";const repo=kind==="base"?RELEASE_BASE_REPOSITORY:RELEASE_UPDATE_REPOSITORY;const branch=kind==="base"?RELEASE_BASE_BRANCH:RELEASE_UPDATE_BRANCH;const s=await source(repo,branch);const version=String(input.version||s.sha.slice(0,12));const channel=kind;const id=`rel_${component}_${version.replace(/[^a-zA-Z0-9_.-]/g,"-")}`;const manifest={sourceRepo:repo,sourceBranch:branch,sourceCommit:s.sha,sourceUrl:s.url,sourceMessage:s.message,sourceDate:s.date,captureKind:kind,packageFormat:kind==="base"?"orbitfs-panel-release":"orbitfs-engine-release"};const result=await db.query("insert into releases(id,component,version,channel,status,title,description,changelog,customer_notes,internal_notes,severity,required,rollout,schema_version,components,manifest,permissions,compatibility,source_commit) values($1,$2,$3,$4,'draft',$5,$6,$7,'','', 'normal',false,'internal','1',$8,$9,'{}','{}',$10) on conflict(component,channel,version) do update set source_commit=excluded.source_commit,manifest=excluded.manifest,updated_at=now() returning *",[id,component,version,channel,String(input.title||`${component} ${version}`),String(input.description||`Captured from ${repo} / ${branch}`),String(input.changelog||s.message),JSON.stringify(kind==="base"?["orbitfs_base"]:["orbitfs_mcp"]),JSON.stringify(manifest),s.sha]);return json(res,200,{ok:true,release:result.rows[0],source:s});}catch(e){return json(res,500,{error:e instanceof Error?e.message:String(e)})}}
