import { Pool } from "pg";
import type { IncomingMessage, ServerResponse } from "node:http";
const DATABASE_URL=String(process.env.DATABASE_URL||"").replace(/[?&]sslmode=[^&]+/i,"");
const db=DATABASE_URL?new Pool({connectionString:DATABASE_URL,max:2,ssl:{rejectUnauthorized:false}}):null;
const MASTER=process.env.MASTER_API_TOKEN||"";
const SUPABASE_URL=(process.env.SUPABASE_URL||"").replace(/\/$/,"");
const SUPABASE_ANON_KEY=process.env.SUPABASE_ANON_KEY||"";
const ADMIN_EMAILS=new Set((process.env.ADMIN_EMAILS||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));
const json=(res:ServerResponse,status:number,v:unknown)=>{res.statusCode=status;res.setHeader("content-type","application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.end(JSON.stringify(v));};
const bearer=(req:IncomingMessage)=>String(req.headers.authorization||"").replace(/^Bearer\s+/i,"").trim();
async function isAdmin(req:IncomingMessage){const t=bearer(req);if(!t)return false;if(MASTER&&t===MASTER)return true;if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return false;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_ANON_KEY,authorization:`Bearer ${t}`}});if(!r.ok)return false;const u=await r.json() as any;return ADMIN_EMAILS.has(String(u.email||"").toLowerCase())||u.app_metadata?.role==="admin";}
const body=(req:IncomingMessage)=>new Promise<Record<string,unknown>>((resolve,reject)=>{const c:Buffer[]=[];req.on("data",x=>c.push(Buffer.from(x)));req.on("end",()=>{try{resolve(c.length?JSON.parse(Buffer.concat(c).toString("utf8")):{});}catch{reject(Error("Request body must be valid JSON"));}});req.on("error",reject);});
export default async function handler(req:IncomingMessage,res:ServerResponse){try{if(!(await isAdmin(req)))return json(res,401,{error:"Administrator authentication is required"});if(!db)return json(res,503,{error:"Database is not configured"});await db.query("alter table master_license_settings add column if not exists release_automation_enabled boolean not null default false; alter table master_license_settings add column if not exists auto_finalize_base boolean not null default false; alter table master_license_settings add column if not exists auto_finalize_updates boolean not null default false; insert into master_license_settings(id) values ('primary') on conflict(id) do nothing");if(req.method==="GET"){const row=(await db.query("select release_automation_enabled,auto_finalize_base,auto_finalize_updates,revision,updated_at from master_license_settings where id='primary'")).rows[0]||{};return json(res,200,{settings:row});}if(req.method!=="PATCH"&&req.method!=="POST")return json(res,405,{error:"Method not allowed"});const input=await body(req);const current=(await db.query("select * from master_license_settings where id='primary'")).rows[0]||{};const row=(await db.query("update master_license_settings set release_automation_enabled=$1,auto_finalize_base=$2,auto_finalize_updates=$3,revision=$4,updated_at=now() where id='primary' returning release_automation_enabled,auto_finalize_base,auto_finalize_updates,revision,updated_at",[input.release_automation_enabled===undefined?current.release_automation_enabled===true:Boolean(input.release_automation_enabled),input.auto_finalize_base===undefined?current.auto_finalize_base===true:Boolean(input.auto_finalize_base),input.auto_finalize_updates===undefined?current.auto_finalize_updates===true:Boolean(input.auto_finalize_updates),Math.max(1,Number(input.revision||current.revision||0)+1)])).rows[0];return json(res,200,{settings:row});}catch(e){return json(res,500,{error:e instanceof Error?e.message:String(e)})}}
